title: Enhancing Speech Auto-Disentanglement for Voice Conversion with IFUB Estimator and Joint Text-Guided Consistent Learning
description: 

theme: jekyll-theme-cayman

# github:
#   repository_url: https://github.com/rechawine/EAD-VC
